### ISSUE TITLE
v0.9.1 の API 説明が一部英語に

### ISSUE THREAD

**Issue by tasogarepg** [nodejsjp/nodejs.org_ja#3]
いつもお世話になっております。
v0.9.1 の 下記 API 説明が英語に戻っているようでした。
- child_process
- cluster
- domain
- http
- tls

**Comment by koichik** [comment]
報告ありがとうございます．
元ファイルが v0.8.8 と違いがなかったので v0.8 ブランチから持ってきたのですが，japanese-v0.8 ブランチから持ってこないといけないのでした．

nodejsjp/node へのプルリクエストと nodejsjp/nodejs.org_ja へのプッシュをしたので反映お願いします＞@meso

**Comment by tasogarepg** [comment]
早速のご対応ありがとうございます。
日本語で最新版の情報が読めて本当に助かっております。

**Comment by meso** [comment]
pushしました
