### ISSUE TITLE
table of contents の訳

### ISSUE THREAD

**Issue by Jxck** [nodejsjp/nodejs.org_ja#4]
http://nodejs.jp/nodejs.org_ja/api/

で表示される table of contents のリンク一覧は、
モジュールの名前になっているので、
訳さないほうがいいと思うんですがどうでしょう？

というか、訳すとどれなのか逆にわかりにくい気が
常々しているのですが。

同意が得られればパッチは書きます。

**Comment by tasogarepg** [comment]
+1
「このドキュメントについて」と「概要」以外は英語のほうが探しやすいですね。

**Comment by koichik** [comment]
元々「File System」とか「UDP/Datagram」とか，モジュール名そのものじゃないものが含まれてます．「Globals」や「STDIO」のようにモジュールじゃないものもあります．
本家によく「TOC をアルファベット順にしろ」という要求がありますが，「自分で見やすいドキュメント作れば？」という流れで JSON 版が提供されるようにもなったし，翻訳版も同じスタンスでいいかと思います．
